name: "User Story"
description: "Template for creating a well-structured user story"
title: "[Story]: "
labels: ["user-story"]
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: Describe the story in As a / I want to / So that format
      placeholder: |
        As a [type of user],
        I want to [perform some action],
        So that [achieve some outcome].
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true
  - type: textarea
    id: definition-of-ready
    attributes:
      label: Definition of Ready
      value: |
        - [ ] Acceptance criteria are clear
        - [ ] User story is estimated
        - [ ] Dependencies identified
    validations:
      required: true
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      value: |
        - [ ] Code review completed
        - [ ] Tests written and passing
        - [ ] Documentation updated
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Any extra context, links, mockups...
    validations:
      required: false
